### ISSUE TITLE
Not Working Any help would be alsome!!

### ISSUE THREAD

**Issue by monomaki2035** [peewpw/Invoke-PSImage#10]
Hello I seem to be getting This error: "Invoke-PSImage : Index was outside the bounds of the array.
At line:1 char:1
+ Invoke-PSImage -Script .\Test.ps1 -Image .\ps_kiwi.png -Out  .\Test-kiwi.png
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Invoke-PSImage], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException,Invoke-PSImage"

When ever I try to run this test : Invoke-PSImage -Script .\Test.ps1 -Image .\ps_kiwi.png -Out Test-kiwi.png

any help would be golden Thanx

**Comment by monomaki2035** [comment]
closed

**Comment by arnydo** [comment]
Did you find a resolution to this?

**Comment by wbadart** [comment]
I ran into this error as well and fixed it by using a smaller input image (~5.5kB).
