### ISSUE TITLE
windows10

### ISSUE THREAD

**Issue by NbR404** [peewpw/Invoke-PSImage#11]
![capture](https://user-images.githubusercontent.com/4534656/41361830-a6b0fb2a-6f38-11e8-8fc5-35c233ded2b8.PNG)

**Comment by killercoderz4** [comment]
please how did you get it to run. i keep getting errors on powershell console while building the image. i followed similar steps in sample explanation

**Comment by peewpw** [comment]
Microsoft correctly identifies that you are up to no good
