### ISSUE TITLE
No effect after opening image created by this script

### ISSUE THREAD

**Issue by hommmi** [peewpw/Invoke-PSImage#15]
I used this
PS>Invoke-PSImage -Script .\Invoke-Mimikatz.ps1 -Image .\kiwi.jpg -Out .\evil-kiwi.png
evil-kiwi.png was created and had lower quality than original (as mentioned) but upon opening nothing happened.
What could be the reason?

**Comment by peewpw** [comment]
You need to run the command the tool outputs in order to execute the payload. Please see the readme for more details.
