### ISSUE TITLE
Nothing happen anything

### ISSUE THREAD

**Issue by mohammedhaffad** [peewpw/Invoke-PSImage#2]
when i open the .png file is nothing happen anything :(

**Comment by Mustafa5798** [comment]
This is a tool to hide a script in pixels of a  picture BUT IT DOESN'T MEAN THIS SCRIPT WILL BE EXECUTED WHEN THE .png OPENED.

**Comment by mohammedhaffad** [comment]
Ohh now i know

**Comment by mahyarx** [comment]
could u describe plz, for which purpose it can be useful ?
