### ISSUE TITLE
One liner doesn't generate

### ISSUE THREAD

**Issue by MrPayne** [peewpw/Invoke-PSImage#3]
I've got the conversion portion working, but when the second file is generated, there is no one-line string generated off of the IEX([System.Text.Encoding]::ASCII.GetString variable.

**Comment by davidgerrard** [comment]
For me, I got the one-liner to execute, but the GetString call was:

IEX([System.Text.Encoding]::ASCII.GetString($o[0..30])) and should have been:

IEX([System.Text.Encoding]::ASCII.GetString($o[0..33]))

**Comment by peewpw** [comment]
GetString definitely needed another byte in its array, but unless you had a one character script, that shouldn't have been the root cause here.
