### ISSUE TITLE
$lpayload + 1?

### ISSUE THREAD

**Issue by jesusninoc** [peewpw/Invoke-PSImage#4]
$pscmd = "sal a New-Object;Add-Type -AssemblyName `"System.Drawing`";`$g= a System.Drawing.Bitmap(`"$Out`");`$o= a Byte[] $array;(0..$lrows)|% {foreach(`$x in (0..$lwidth)){`$p=`$g.GetPixel(`$x,`$_);`$o[`$_*$width+`$x]=([math]::Floor((`$p.B -band 15)*16) -bor (`$p.G -band 15))}};`$g.Dispose();IEX([System.Text.Encoding]::ASCII.GetString(`$o[0..**($lpayload+1)**]))"

**Comment by peewpw** [comment]
Yes! Just fixed this.
I didn't notice for a long time since almost any script ends with a newline.
