### ISSUE TITLE
the term 'xxxxxx' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by plissje** [peewpw/Invoke-PSImage#8]
Hi,
Trying to run this via a simple script, that will just 'write-output 123', and I'm getting an error when trying to execute the one-liner:
![screenshot_3](https://user-images.githubusercontent.com/35014400/34471724-eaf63a6c-ef58-11e7-9a8f-76cc8d8fc6cb.png)

any ideas? :)

**Comment by peewpw** [comment]
I cannot reproduce this one. I would guess the encoding on your input file is wonky. Try recreating that file and see if that helps.

You can also try
[IO.File]::ReadAllText("C:\temp\Invoke-mimikatz.ps1")
and see if the script displays as expected. That is how the tool gets the script content to encode.
