### ISSUE TITLE
Either not working or misunderstanding instructions

### ISSUE THREAD

**Issue by altjx** [peewpw/Invoke-PSImage#9]
So from what I understand in the instructions, you simply provide it a script that you want to execute when an image is opened, and an image, is that correct? If so, I have a file called script.ps1, which essentially just submits back the username of the user logged onto the computer back to a web page. Extremely small script -- approximately 20 lines of code.

I can run this script manually with no problem; however, when trying to embed it into the jpeg file (exported to PNG), nothing happens when opening the PNG file. Of course the PNG looks just fine --
 I can see the image, etc. No error is generated either when exporting it. Here's the command that I'm entering: 

```
Import-Module .\Invoke-PSImage.ps1
Invoke-PSImage -script .\script.ps1 -Image .\image.jpeg -Out .\result.png
```

Again, running the script from the PowerShell prompt, it works just fine. Taking this same working Powershell script and trying to embed it into the JPEG picture (which is 4252 x 2835) and is significantly smaller than Invoke-Mimikatz, doesn't seem to be doing anything. The JPEG goes from about 3MB to an exported PNG file of about 28.5MB

Can you let me know what I'm doing wrong, if anything? Thanks!

**Comment by peewpw** [comment]
The png file does not execute itself, it just contains the script data. You will need to run the generated command to read the script data from the image and execute it.

**Comment by altjx** [comment]
So if I understand correctly, you can't send the PNG file to someone, have them open it, and the script data content runs? Because I thought that's what the purpose of this was. Perhaps I misunderstood. 

Sent from my iPhone

On Feb 4, 2018, at 12:08 PM, Barrett Adams <notifications@github.com> wrote:

The png file does not execute itself, it just contains the script data. You will need to run the generated command to read the script data from the image and execute it.
